version: '2'
volumes:
    dashboard-data:
    sensor-data:
services:
  sensor:
    build: ./database
    privileged: true
    restart: never
    network_mode: host
    ports:
        - '7878'
  dashboard:
    image: balenablocks/dashboard:raspberrypi3
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
  connector:
    image: balenablocks/connector:raspberrypi3
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
    privileged: true # necessary to change container hostname
  mqtt:
    image: arm32v6/eclipse-mosquitto@sha256:ec3e1dbb9e198ff04d62c2d0f6eff74cad7438c7d080b89a28428fb96c8479c4
    ports:
      - "1883:1883"
    restart: always
